name: .NET

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Build and Compress
      run: .\Module\src\Build.ps1
    - name: Automatic Releases
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "PSModule_Latest"
          prerelease: false
          title: "WindowsUtils PowerShell Module"
          files: WindowsUtilsModule.zip