name: .NET

on:
  push:
    branches: [ "main" ]

env:
  PSGAL_APIKEY: ${{ secrets.PSGAL_APIKEY }}

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v3.0.3
      with:
        dotnet-version: 7.0.x
    - name: Build and Compress
      run: |
        .\Build.ps1 -psgsec "$env:PSGAL_APIKEY"
    - name: Automatic Releases
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "Latest"
          prerelease: false
          title: "WindowsUtils PowerShell Module"
          files: WindowsUtils.zip
